name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        java: ['openjdk@1.16.0', 'openjdk@1.11.0-2', 'zulu@1.8.282']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - run: sbt test